application: cost-logger
version: v3
runtime: go
threadsafe: true
api_version: go1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: _go_app
  secure: always

# Static assets
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

- url: /
  static_dir: dist
  secure: always

skip_files:
- ^node_modules/(.*)$
- ^src/(.*)$
- ^(.*/)?.*\.ts$
- ^(.*/)?.*\.map$
